name: '自动同步'

on: [push, delete]

jobs:
  sync:
    name: '同步仓库'
    runs-on: ubuntu-22.04
    steps:
      - name: '检出仓库'
        uses: actions/checkout@v1
      - name: '同步到仓库'
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            ${{ secrets.REPO }}
          ssh_private_key:
            ${{ secrets.PRIVATE_KEY }}